# Generated by Django 4.0.4 on 2022-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
