# Generated by Django 4.0.4 on 2022-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_feedback_options_alter_block_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockimage',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег'),
        ),
    ]
