# Generated by Django 4.0.4 on 2022-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_botusers_alter_feedback_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата и время отработки заявки'),
        ),
    ]
