# Generated by Django 4.0.4 on 2022-08-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_feedback_datetime_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата и время отработки заявки'),
        ),
    ]
