# Generated by Django 4.0.4 on 2022-08-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_feedback_datetime_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_last_change',
        ),
        migrations.DeleteModel(
            name='BotUsers',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
