# Generated by Django 4.0.4 on 2022-08-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_botusers_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отработки заявки'),
        ),
    ]
