# Generated by Django 4.0.4 on 2022-08-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_feedback_datetime_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_last_change',
        ),
    ]
