# Generated by Django 4.0.4 on 2022-08-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_feedback_user_last_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUsers',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='datetime_complete',
        ),
    ]
