# Generated by Django 4.0.4 on 2022-08-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_botusers_remove_feedback_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('userid', models.IntegerField(unique=True, verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Адресаты рассылки',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Отметка о выполнении'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отработки заявки'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_last_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.botusers'),
        ),
    ]
