# Generated by Django 4.0.4 on 2022-08-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_feedback_datetime_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отработки заявки'),
        ),
    ]
