# Generated by Django 4.0.4 on 2022-08-05 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_feedback_datetime_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 21, 18, 33, 326750, tzinfo=utc), verbose_name='Дата и время создания'),
        ),
    ]
