# Generated by Django 4.0.4 on 2022-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_feedback_datetime_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
